# -*- coding: utf-8 -*-
"""Milano-Cortina sentiment and topic modelling part 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PY-BorPFBa1YBNhb2R6bHTG2KslP5MbI

**Eye on next olympic games
Analysis of the sentiment analysis and topic modelling after Milan-Cortina bid in 2026**

**Student:Alessio Tesse, 892774@stud.unive.it
Course of Literary and linguistic Computing
Academic year: 2022-2023**

The Milan-cortina 2026 olympic Deabate
On June 24th in Lausanne, the 2026 Winter Games were awarded to Milan and Cortina. My aim is to represent the sentiment analysis through tweets from the days before and the days after. Another purpose of my work is topic modelling through lemmatization and the use of LDA. And it is interesting to understand the debate that was created in social circles immediately after the victory because usually the Olympics in Italy require a great economic effort and also bureaucratic and management problems. Nevertheless, Italy won its third Winter Olympics at the expense of Stockholm. The social debate, as I said before, saw people who had a positive view of the Olympic Games and people who do not look favourably on the awarding of the Olympics because it involves a waste of public money

First of all i'm going to import all the libraries useful to upload all the following files
"""

#import all the libraries
from textblob import TextBlob
from wordcloud import WordCloud
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

import os

import csv

"""Here i import the os because i found some problems to upload the csv file"""

os.getcwd()



"""Here i upload the dataset with all the tweets about Milano-Cortina"""

df = pd.read_csv('mico.csv')

df

"""In this part i started the sentiment analysis, starting from text cleaning

First of all sentiment analysis is a field that studies people's opinion and sentiment and so forth. Moreover linguistic and NLP have a long history. Starting from 2000 things have changed and there were an arrange of application, the industry of sentiment analysis has flourished due to ploliferation of commercial application. It offers a lot of challenging research problem. Finally we have also a huge volume of data in the social media on the Web
"""

def cleanText(text):
    text = text.lower()
    text = re.sub(r"https\S+|www\S+https\S+", '',text)
    text = re.sub(r'#','',text)
    text = re.sub(r'@','',text)
    return text


df['Tweet']= df['Tweet'].apply(cleanText)

#Show the cleaned text
df

"""Here i divided the subjectivity and polarity, the subjectivity distinguishes sentence that express factual info from sentences and express subjective opinions and views. While polarity refers to the overall sentiment conveyed by a particular text, phrase or word"""

#find the subjectivity
def getSubjectivity(text):
    return TextBlob(text).sentiment.subjectivity
#find the polarity
def getPolarity(text):
    return TextBlob(text).sentiment.polarity

#create two new columns
df['Subjectivity'] = df['Tweet'].apply(getSubjectivity)
df['Polarity'] = df['Tweet'].apply(getPolarity)

#show the dataframe
df

#create a new function to compute negative, positive and neutral

def getAnalysis(score):
    if score < 0.25:
        return 'Negative'
    elif score == 0.50:
        return 'Neutral'
    else :
        return 'Positive'

df['Analysis'] = df['Polarity'].apply(getAnalysis)

#show the dataframe
df

#print the positive tweet
j=1
sorteddf = df.sort_values(by=['Analysis'])
for i in range(0, sorteddf.shape[0]):
    if(sorteddf['Analysis'][i] == 'Positive'):
        print(str(j) + ') '+ sorteddf['Tweet'][i])
        print()
        j = j+1

"""Here we can see the positive tweets with the value greater than 0.50 because some tweets are ironic or negative but the computer recognizes as positive. But in this case we can see happiness and trepidation for the games"""

#print the negative tweet
j=1
sorteddf = df.sort_values(by=['Analysis'])
for i in range(0, sorteddf.shape[0]):
    if(sorteddf['Analysis'][i] == 'Negative'):
        print(str(j) + ') '+ sorteddf['Tweet'][i])
        print()
        j = j+1

"""On the other hand we see a pessimistic or angry point of view about some citiziens because they don't care about the positive impact of Milan-Cortina or some people are angry to M5s especially people from Rome, because in 2016 the former mayor didn't allow to advance the olympic bid

Sentiment analysis is also used for other topics not only politics also sport in this case, because sports events are globally and in my case I analyzed the impact of the future olympic winter games in 2026 because more politicians were happy despite their starting idea or so forth. The importance of olympics is very huge because is not only sport event but also: economic growth, modern transport and new sports arenas

Bibliography
https://www.coni.it/it/news/16270-il-grande-giorno-in-corso-la-sessione-cio-per-assegnare-i-giochi-2026-presentazione-tecnica-per-milano-cortina.html

Liu Bing, Sentiment Analysis and Opinion mining
"""